base:
  project: storesales-project
  random_state: 42
  target_col: item_outlet_sales

data_source:
  train_source: data_given/Train.csv
  test_source: data_given/Test.csv

connect_cassandra:
  cloud_config: C:\Users\Manu\Documents\ineuron\Internship\StoreSalesPrediction\secure-connect-ineuron.zip
  client_id: agUmJJZtyYDUGumhwyWXTvZv
  client_secret: kxJ40+kUaRKly3AQH7WlImNwr0tlsYR3ZexMJ4F+q0hr_u+D8zFhw4Yg4NJTuipHhbjhDPX3EgpfWgwFHrZ,tLgcbpNzo_Z_4OE4frohn+ao9cmavKNuX4PFzF8xUnfe
  
cassandra_db:
  keyspace: store_sales
  data_table: big_mart
  define_columns: Item_Identifier varchar PRIMARY KEY, Item_Weight varchar, Item_Fat_Content varchar, Item_Visibility varchar,  Item_Type varchar, Item_MRP varchar, Outlet_Identifier varchar, Outlet_Establishment_Year varchar, Outlet_Size varchar, Outlet_Location_type varchar, Outlet_Type varchar, Item_Outlet_Sales varchar, source varchar
  columns: Item_Identifier, Item_Weight, Item_Fat_Content, Item_Visibility, Item_Type, Item_MRP, Outlet_Identifier, Outlet_Establishment_Year, Outlet_Size, Outlet_Location_Type, Outlet_Type, Item_Outlet_Sales, source
  
load_data:
  raw_data_path: data/raw/raw_data.csv

preprocess_data:
  processed_data: data/pre-processed/data.csv
  
one_hot_encoding:
  data_path: data/one_hot_encoded/one_hot_encoded.csv
  id_columns: [item_identifier, outlet_identifier]
  target: item_outlet_sales 
  source: source
  columns: ['item_fat_content','outlet_location_type','outlet_size','outlet_type', 'item_type_combined']

split_data:
  train_path: data/split-data/train.csv
  test_path: data/split-data/test.csv
  validation_path: data/split-data/val.csv
  val_size: 0.2

test_prediction:
  output_path: data/predicted_test/test.csv

estimators:
  DecisionTree:
    params:
      max_depth: 8
      min_samples_leaf: 150
      
cross_validation:
  cv: 20
  scoring: neg_mean_squared_error

model_dir: saved_models
  
reports:
  params: report/params.json
  scores: report/scores.json

#webapp_model_dir: saved_models

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: Decision Tree regression
  run_name: mlops
  registered_model_name: DecisionTreeStoreSalesModel
  remote_server_uri: http://127.0.0.1:5000